[project]
protostar-version = "0.8.1"
lib-path = "lib"

[contracts]
main = ["src/main.cairo"]

["protostar.shared_command_configs"]
cairo-path = ["lib/cairo_contracts/src", "lib/cairopen_contracts/src"]


